### ISSUE TITLE
Error: onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'TopK_111_input_cast_0' of node: 

### ISSUE THREAD

**Issue by seungtaek94** [microsoft/onnxconverter-common#240]
Hi. I try  to convert superpoint float32 model to float16 using following code.

```Python
import onnx
from onnxconverter_common.float16 import convert_float_to_float16


if __name__=="__main__":
    WIDTH = 512
    HEIGHT = 256
    MAX_KEY = 200

    onnx_model32 = onnx.load(f"super_point_p{MAX_KEY}_w{WIDTH}_h{HEIGHT}_nojit.onnx")
    onnx_model16 = convert_float_to_float16(onnx_model32)  
    onnx.save(onnx_model16, f"super_point_p{MAX_KEY}_w{WIDTH}_h{HEIGHT}_fp16_nojit.onnx")
    
    onnx.checker.check_model(onnx_model16)
```

It successfully convert to fp16 model without any messages but when i check the converted fp16 model that cause following error.
```
Traceback (most recent call last):
  File "/home/seungtaek/superpoint/convertonnxfloat2float16.py", line 31, in <module>
    onnx.checker.check_model(onnx_model16)
  File "/home/seungtaek/anaconda3/envs/pytorch_build/lib/python3.9/site-packages/onnx/checker.py", line 106, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'TopK_111_input_cast_0' of node: 
name: TopK_111 OpType: TopK
 is not output of any previous nodes.
```

I linked above two model one is fp32 the other is converted fp16.
[download models](https://drive.google.com/drive/folders/1DjN8-67I2puJUuyJDU8ev9HcrrATz04Z?usp=sharing)

How can I solve this problem?

Thanks.

**Comment by xiaowuhu** [comment]
@seungtaek94 Hi, if the fp16 model can do inference correctly, I think you can ignore this error message. I checked the fp16 model, the TopK_111_output_cast_0 does have parent node (TopK_111_input_cast0).
